# Generated by Django 5.1 on 2024-09-25 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0002_booking_check_in_date_booking_check_out_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="check_in_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="check_out_date",
        ),
    ]
